/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TebakGambar;

/**
 *
 * @author hamka
 */
public class GameFrame extends javax.swing.JFrame {

    /**
     * Creates new form GameFrame
     */
    public GameFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bebek = new javax.swing.JLabel();
        Labeldes = new javax.swing.JLabel();
        btnbermain = new javax.swing.JButton();
        btnpahlawan = new javax.swing.JButton();
        btnmakanan = new javax.swing.JButton();
        btnadat = new javax.swing.JButton();
        btnkota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        bebek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TebakGambar/XOsX.gif"))); // NOI18N

        Labeldes.setBackground(new java.awt.Color(0, 0, 0));
        Labeldes.setFont(new java.awt.Font("Cascadia Mono", 1, 14)); // NOI18N
        Labeldes.setForeground(new java.awt.Color(0, 0, 0));
        Labeldes.setText("   Tebak Makananan Khas Indonesia");
        Labeldes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnbermain.setBackground(new java.awt.Color(0, 102, 204));
        btnbermain.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnbermain.setForeground(new java.awt.Color(255, 255, 255));
        btnbermain.setText("Bermain");
        btnbermain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbermainActionPerformed(evt);
            }
        });

        btnpahlawan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnpahlawan.setText("Pahlawan");
        btnpahlawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpahlawanActionPerformed(evt);
            }
        });

        btnmakanan.setBackground(new java.awt.Color(0, 102, 204));
        btnmakanan.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnmakanan.setText("Makanan");
        btnmakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmakananActionPerformed(evt);
            }
        });

        btnadat.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnadat.setText("Pakaian adat");
        btnadat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadatActionPerformed(evt);
            }
        });

        btnkota.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnkota.setText("Kota");
        btnkota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bebek, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Labeldes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnmakanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnkota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpahlawan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnadat))
                    .addComponent(btnbermain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(bebek)
                .addGap(33, 33, 33))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpahlawan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnadat, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnkota, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Labeldes, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnbermain, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnkotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkotaActionPerformed
        GameFramekota nextkota = new GameFramekota();
        nextkota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnkotaActionPerformed

    private void btnadatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadatActionPerformed
        GameFrameAdat nextadat = new GameFrameAdat();
        nextadat.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnadatActionPerformed

    private void btnmakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmakananActionPerformed

    private void btnpahlawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpahlawanActionPerformed
        GameFramePahlawan nextpahlawan = new GameFramePahlawan();
        nextpahlawan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnpahlawanActionPerformed

    private void btnbermainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbermainActionPerformed
        InGame nextgame = new InGame();
        nextgame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbermainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labeldes;
    private javax.swing.JLabel bebek;
    private javax.swing.JButton btnadat;
    private javax.swing.JButton btnbermain;
    private javax.swing.JButton btnkota;
    private javax.swing.JButton btnmakanan;
    private javax.swing.JButton btnpahlawan;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
